import Container from "./components/Container";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`flex min-h-screen flex-col bg-green-200 ${inter.className}`}
      >
        <header className="bg-emerald-600 w-full sticky left-0 top-0 py-5">
          <Container>
            <div className="flex justify-between items-center min-w-full">
              <div className="py-3 leading-10 tracking-wider text-center font-medium uppercase text-white text-xl">
                Simple{" "}
                <span className="text-red-600 font-extrabold">Calculator</span>
              </div>
              <div className="flex gap-3 justify-center items-center text-center">
                <button className="p-3 border cursor-pointer rounded-lg bg-transparent hover:bg-red-600 transition-all duration-150 delay-75">
                  <div className="text-white font-extrabold">Profile</div>
                </button>
                <button className="p-3 border cursor-pointer rounded-lg bg-transparent hover:bg-red-600 transition-all duration-150 delay-75">
                  <div className="text-white font-extrabold">Login</div>
                </button>
              </div>
            </div>
          </Container>
        </header>
        <Container>
          <main className="pt-3">{children}</main>
        </Container>
      </body>
    </html>
  );
}
